/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BookServiceRequest = IDL.Record({
  'date' : Time,
  'artistId' : IDL.Principal,
  'serviceId' : IDL.Nat,
});
export const CalculateTimeRangeRequest = IDL.Record({
  'startTime' : IDL.Text,
  'endDate' : Time,
  'endTime' : IDL.Text,
  'startDate' : Time,
});
export const CreateArtistProfileRequest = IDL.Record({
  'bio' : IDL.Text,
  'contactInfo' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});
export const CreateArtistProfileResponse = IDL.Record({ 'id' : IDL.Text });
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'serviceType' : IDL.Text,
  'duration' : IDL.Nat,
  'clientId' : IDL.Principal,
  'date' : Time,
  'time' : IDL.Text,
  'artistId' : IDL.Principal,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Gig = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'artistId' : IDL.Principal,
  'description' : IDL.Text,
  'deliveryTime' : Time,
  'pricing' : IDL.Nat,
});
export const JobOffering = IDL.Record({
  'id' : IDL.Text,
  'description' : IDL.Text,
  'deadline' : Time,
  'employer' : IDL.Principal,
  'jobTitle' : IDL.Text,
  'budget' : IDL.Nat,
});
export const CreateServiceRequest = IDL.Record({
  'duration' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Opt(IDL.Text),
  'price' : IDL.Nat,
});
export const DeleteServiceRequest = IDL.Record({ 'id' : IDL.Nat });
export const Music = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'audioFileBlob' : ExternalBlob,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'artist' : IDL.Principal,
  'price' : IDL.Nat,
  'uploadDate' : IDL.Int,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'subcategory' : IDL.Text,
  'artistId' : IDL.Principal,
  'productImages' : IDL.Vec(ExternalBlob),
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const ArtistProfile = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'contactInfo' : IDL.Text,
  'portfolioImages' : IDL.Vec(ExternalBlob),
  'skills' : IDL.Vec(IDL.Text),
});
export const AllArtistProfilesResponse = IDL.Record({
  'profiles' : IDL.Vec(ArtistProfile),
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Nat,
  'name' : IDL.Text,
  'artistId' : IDL.Principal,
  'description' : IDL.Text,
  'category' : IDL.Opt(IDL.Text),
  'price' : IDL.Nat,
});
export const GetAllServicesResponse = IDL.Record({
  'services' : IDL.Vec(Service),
});
export const ArtistProfileResponse = IDL.Record({ 'profile' : ArtistProfile });
export const Range = IDL.Record({ 'end' : Time, 'start' : Time });
export const GetAvailableTimeSlotsResponse = IDL.Record({
  'timeSlots' : IDL.Vec(IDL.Text),
});
export const GetBookingsByCodeResponse = IDL.Record({
  'bookings' : IDL.Vec(Booking),
});
export const GetServicesByArtistResponse = IDL.Record({
  'services' : IDL.Vec(Service),
});
export const PricingRule = IDL.Record({
  'maxPrice' : IDL.Nat,
  'minPrice' : IDL.Nat,
});
export const StoreProductFilter = IDL.Record({
  'maxPrice' : IDL.Opt(IDL.Nat),
  'available' : IDL.Opt(IDL.Bool),
  'category' : IDL.Opt(IDL.Text),
  'rating' : IDL.Opt(IDL.Nat),
  'minPrice' : IDL.Opt(IDL.Nat),
});
export const StoreProductConfig = IDL.Record({
  'productCategoryLimit' : IDL.Nat,
  'lowStockThreshold' : IDL.Nat,
  'returnPeriodDays' : IDL.Nat,
  'productCategories' : IDL.Vec(IDL.Text),
  'freeShippingThreshold' : IDL.Nat,
  'productTags' : IDL.Vec(IDL.Text),
  'pricingRules' : PricingRule,
  'filterOptions' : IDL.Vec(StoreProductFilter),
  'inventoryTrackingEnabled' : IDL.Bool,
  'requireApprovalFor' : IDL.Record({
    'gigs' : IDL.Bool,
    'jobs' : IDL.Bool,
    'products' : IDL.Bool,
  }),
  'defaultCurrency' : IDL.Text,
  'featuredProducts' : IDL.Vec(IDL.Text),
  'productStatuses' : IDL.Vec(IDL.Text),
  'taxRate' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeStoreConfig = IDL.Record({
  'webhookSecret' : IDL.Text,
  'testMode' : IDL.Bool,
  'secretKey' : IDL.Text,
  'currency' : IDL.Text,
  'publishableKey' : IDL.Text,
  'webhookEndpoint' : IDL.Text,
});
export const SearchServicesByCategoryResponse = IDL.Record({
  'services' : IDL.Vec(Service),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateServiceRequest = IDL.Record({
  'duration' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Opt(IDL.Text),
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPortfolioImage' : IDL.Func([ExternalBlob], [], []),
  'assignAdminPrivileges' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookService' : IDL.Func([BookServiceRequest], [], []),
  'calculateTimeRange' : IDL.Func([CalculateTimeRangeRequest], [], []),
  'createArtistProfile' : IDL.Func(
      [CreateArtistProfileRequest],
      [CreateArtistProfileResponse],
      [],
    ),
  'createBooking' : IDL.Func([Booking], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createGig' : IDL.Func([Gig], [], []),
  'createJobOffering' : IDL.Func([JobOffering], [], []),
  'createMusic' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(ExternalBlob), IDL.Text],
      [],
      [],
    ),
  'createProductFromImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'createService' : IDL.Func([CreateServiceRequest], [], []),
  'deleteBooking' : IDL.Func([IDL.Text], [], []),
  'deleteGig' : IDL.Func([IDL.Text], [], []),
  'deleteJobOffering' : IDL.Func([IDL.Text], [], []),
  'deleteMusic' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'deleteService' : IDL.Func([DeleteServiceRequest], [], []),
  'findBookingsByArtist' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'findBookingsByDate' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'findGigsByDeliveryTime' : IDL.Func([], [IDL.Vec(Gig)], ['query']),
  'findGigsByPricing' : IDL.Func([], [IDL.Vec(Gig)], ['query']),
  'findJobOfferingsByBudget' : IDL.Func([], [IDL.Vec(JobOffering)], ['query']),
  'findJobOfferingsByDeadline' : IDL.Func(
      [],
      [IDL.Vec(JobOffering)],
      ['query'],
    ),
  'findMusicByArtist' : IDL.Func([IDL.Principal], [IDL.Vec(Music)], ['query']),
  'findMusicByPrice' : IDL.Func([], [IDL.Vec(Music)], ['query']),
  'findProductsByArtist' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'findProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllArtists' : IDL.Func([], [AllArtistProfilesResponse], ['query']),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllGigs' : IDL.Func([], [IDL.Vec(Gig)], ['query']),
  'getAllJobOfferings' : IDL.Func([], [IDL.Vec(JobOffering)], ['query']),
  'getAllMusic' : IDL.Func([], [IDL.Vec(Music)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllServices' : IDL.Func([], [GetAllServicesResponse], ['query']),
  'getArtistById' : IDL.Func([IDL.Text], [ArtistProfileResponse], ['query']),
  'getAvailableTimeSlots' : IDL.Func(
      [Range],
      [GetAvailableTimeSlotsResponse],
      ['query'],
    ),
  'getBookingsByCode' : IDL.Func(
      [IDL.Text],
      [GetBookingsByCodeResponse],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMusicById' : IDL.Func([IDL.Text], [IDL.Opt(Music)], ['query']),
  'getServicesByArtist' : IDL.Func(
      [IDL.Principal],
      [GetServicesByArtistResponse],
      ['query'],
    ),
  'getStoreProductConfig' : IDL.Func([], [StoreProductConfig], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getStripeStoreConfig' : IDL.Func([], [StripeStoreConfig], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'searchServicesByCategory' : IDL.Func(
      [IDL.Text],
      [SearchServicesByCategoryResponse],
      ['query'],
    ),
  'setRequireApprovalFor' : IDL.Func([IDL.Bool, IDL.Bool, IDL.Bool], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setStripeStoreConfig' : IDL.Func([StripeStoreConfig], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBooking' : IDL.Func([Booking], [], []),
  'updateGig' : IDL.Func([Gig], [], []),
  'updateJobOffering' : IDL.Func([JobOffering], [], []),
  'updateMusic' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(ExternalBlob), IDL.Text],
      [],
      [],
    ),
  'updateService' : IDL.Func([IDL.Nat, UpdateServiceRequest], [], []),
  'updateStoreProductConfig' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        PricingRule,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'uploadImage' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BookServiceRequest = IDL.Record({
    'date' : Time,
    'artistId' : IDL.Principal,
    'serviceId' : IDL.Nat,
  });
  const CalculateTimeRangeRequest = IDL.Record({
    'startTime' : IDL.Text,
    'endDate' : Time,
    'endTime' : IDL.Text,
    'startDate' : Time,
  });
  const CreateArtistProfileRequest = IDL.Record({
    'bio' : IDL.Text,
    'contactInfo' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  const CreateArtistProfileResponse = IDL.Record({ 'id' : IDL.Text });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'serviceType' : IDL.Text,
    'duration' : IDL.Nat,
    'clientId' : IDL.Principal,
    'date' : Time,
    'time' : IDL.Text,
    'artistId' : IDL.Principal,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Gig = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'artistId' : IDL.Principal,
    'description' : IDL.Text,
    'deliveryTime' : Time,
    'pricing' : IDL.Nat,
  });
  const JobOffering = IDL.Record({
    'id' : IDL.Text,
    'description' : IDL.Text,
    'deadline' : Time,
    'employer' : IDL.Principal,
    'jobTitle' : IDL.Text,
    'budget' : IDL.Nat,
  });
  const CreateServiceRequest = IDL.Record({
    'duration' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Opt(IDL.Text),
    'price' : IDL.Nat,
  });
  const DeleteServiceRequest = IDL.Record({ 'id' : IDL.Nat });
  const Music = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'audioFileBlob' : ExternalBlob,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'artist' : IDL.Principal,
    'price' : IDL.Nat,
    'uploadDate' : IDL.Int,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'subcategory' : IDL.Text,
    'artistId' : IDL.Principal,
    'productImages' : IDL.Vec(ExternalBlob),
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ArtistProfile = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'contactInfo' : IDL.Text,
    'portfolioImages' : IDL.Vec(ExternalBlob),
    'skills' : IDL.Vec(IDL.Text),
  });
  const AllArtistProfilesResponse = IDL.Record({
    'profiles' : IDL.Vec(ArtistProfile),
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Nat,
    'name' : IDL.Text,
    'artistId' : IDL.Principal,
    'description' : IDL.Text,
    'category' : IDL.Opt(IDL.Text),
    'price' : IDL.Nat,
  });
  const GetAllServicesResponse = IDL.Record({ 'services' : IDL.Vec(Service) });
  const ArtistProfileResponse = IDL.Record({ 'profile' : ArtistProfile });
  const Range = IDL.Record({ 'end' : Time, 'start' : Time });
  const GetAvailableTimeSlotsResponse = IDL.Record({
    'timeSlots' : IDL.Vec(IDL.Text),
  });
  const GetBookingsByCodeResponse = IDL.Record({
    'bookings' : IDL.Vec(Booking),
  });
  const GetServicesByArtistResponse = IDL.Record({
    'services' : IDL.Vec(Service),
  });
  const PricingRule = IDL.Record({
    'maxPrice' : IDL.Nat,
    'minPrice' : IDL.Nat,
  });
  const StoreProductFilter = IDL.Record({
    'maxPrice' : IDL.Opt(IDL.Nat),
    'available' : IDL.Opt(IDL.Bool),
    'category' : IDL.Opt(IDL.Text),
    'rating' : IDL.Opt(IDL.Nat),
    'minPrice' : IDL.Opt(IDL.Nat),
  });
  const StoreProductConfig = IDL.Record({
    'productCategoryLimit' : IDL.Nat,
    'lowStockThreshold' : IDL.Nat,
    'returnPeriodDays' : IDL.Nat,
    'productCategories' : IDL.Vec(IDL.Text),
    'freeShippingThreshold' : IDL.Nat,
    'productTags' : IDL.Vec(IDL.Text),
    'pricingRules' : PricingRule,
    'filterOptions' : IDL.Vec(StoreProductFilter),
    'inventoryTrackingEnabled' : IDL.Bool,
    'requireApprovalFor' : IDL.Record({
      'gigs' : IDL.Bool,
      'jobs' : IDL.Bool,
      'products' : IDL.Bool,
    }),
    'defaultCurrency' : IDL.Text,
    'featuredProducts' : IDL.Vec(IDL.Text),
    'productStatuses' : IDL.Vec(IDL.Text),
    'taxRate' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeStoreConfig = IDL.Record({
    'webhookSecret' : IDL.Text,
    'testMode' : IDL.Bool,
    'secretKey' : IDL.Text,
    'currency' : IDL.Text,
    'publishableKey' : IDL.Text,
    'webhookEndpoint' : IDL.Text,
  });
  const SearchServicesByCategoryResponse = IDL.Record({
    'services' : IDL.Vec(Service),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateServiceRequest = IDL.Record({
    'duration' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Opt(IDL.Text),
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPortfolioImage' : IDL.Func([ExternalBlob], [], []),
    'assignAdminPrivileges' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookService' : IDL.Func([BookServiceRequest], [], []),
    'calculateTimeRange' : IDL.Func([CalculateTimeRangeRequest], [], []),
    'createArtistProfile' : IDL.Func(
        [CreateArtistProfileRequest],
        [CreateArtistProfileResponse],
        [],
      ),
    'createBooking' : IDL.Func([Booking], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createGig' : IDL.Func([Gig], [], []),
    'createJobOffering' : IDL.Func([JobOffering], [], []),
    'createMusic' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(ExternalBlob),
          IDL.Text,
        ],
        [],
        [],
      ),
    'createProductFromImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'createService' : IDL.Func([CreateServiceRequest], [], []),
    'deleteBooking' : IDL.Func([IDL.Text], [], []),
    'deleteGig' : IDL.Func([IDL.Text], [], []),
    'deleteJobOffering' : IDL.Func([IDL.Text], [], []),
    'deleteMusic' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'deleteService' : IDL.Func([DeleteServiceRequest], [], []),
    'findBookingsByArtist' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'findBookingsByDate' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'findGigsByDeliveryTime' : IDL.Func([], [IDL.Vec(Gig)], ['query']),
    'findGigsByPricing' : IDL.Func([], [IDL.Vec(Gig)], ['query']),
    'findJobOfferingsByBudget' : IDL.Func(
        [],
        [IDL.Vec(JobOffering)],
        ['query'],
      ),
    'findJobOfferingsByDeadline' : IDL.Func(
        [],
        [IDL.Vec(JobOffering)],
        ['query'],
      ),
    'findMusicByArtist' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Music)],
        ['query'],
      ),
    'findMusicByPrice' : IDL.Func([], [IDL.Vec(Music)], ['query']),
    'findProductsByArtist' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'findProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllArtists' : IDL.Func([], [AllArtistProfilesResponse], ['query']),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllGigs' : IDL.Func([], [IDL.Vec(Gig)], ['query']),
    'getAllJobOfferings' : IDL.Func([], [IDL.Vec(JobOffering)], ['query']),
    'getAllMusic' : IDL.Func([], [IDL.Vec(Music)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllServices' : IDL.Func([], [GetAllServicesResponse], ['query']),
    'getArtistById' : IDL.Func([IDL.Text], [ArtistProfileResponse], ['query']),
    'getAvailableTimeSlots' : IDL.Func(
        [Range],
        [GetAvailableTimeSlotsResponse],
        ['query'],
      ),
    'getBookingsByCode' : IDL.Func(
        [IDL.Text],
        [GetBookingsByCodeResponse],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMusicById' : IDL.Func([IDL.Text], [IDL.Opt(Music)], ['query']),
    'getServicesByArtist' : IDL.Func(
        [IDL.Principal],
        [GetServicesByArtistResponse],
        ['query'],
      ),
    'getStoreProductConfig' : IDL.Func([], [StoreProductConfig], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getStripeStoreConfig' : IDL.Func([], [StripeStoreConfig], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'searchServicesByCategory' : IDL.Func(
        [IDL.Text],
        [SearchServicesByCategoryResponse],
        ['query'],
      ),
    'setRequireApprovalFor' : IDL.Func([IDL.Bool, IDL.Bool, IDL.Bool], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setStripeStoreConfig' : IDL.Func([StripeStoreConfig], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBooking' : IDL.Func([Booking], [], []),
    'updateGig' : IDL.Func([Gig], [], []),
    'updateJobOffering' : IDL.Func([JobOffering], [], []),
    'updateMusic' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(ExternalBlob),
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateService' : IDL.Func([IDL.Nat, UpdateServiceRequest], [], []),
    'updateStoreProductConfig' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          PricingRule,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'uploadImage' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };