/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AllArtistProfilesResponse { 'profiles' : Array<ArtistProfile> }
export interface ArtistProfile {
  'id' : string,
  'bio' : string,
  'contactInfo' : string,
  'portfolioImages' : Array<ExternalBlob>,
  'skills' : Array<string>,
}
export interface ArtistProfileResponse { 'profile' : ArtistProfile }
export interface BookServiceRequest {
  'date' : Time,
  'artistId' : Principal,
  'serviceId' : bigint,
}
export interface Booking {
  'id' : string,
  'serviceType' : string,
  'duration' : bigint,
  'clientId' : Principal,
  'date' : Time,
  'time' : string,
  'artistId' : Principal,
}
export interface CalculateTimeRangeRequest {
  'startTime' : string,
  'endDate' : Time,
  'endTime' : string,
  'startDate' : Time,
}
export interface CreateArtistProfileRequest {
  'bio' : string,
  'contactInfo' : string,
  'skills' : Array<string>,
}
export interface CreateArtistProfileResponse { 'id' : string }
export interface CreateServiceRequest {
  'duration' : bigint,
  'name' : string,
  'description' : string,
  'category' : [] | [string],
  'price' : bigint,
}
export interface DeleteServiceRequest { 'id' : bigint }
export type ExternalBlob = Uint8Array;
export interface GetAllServicesResponse { 'services' : Array<Service> }
export interface GetAvailableTimeSlotsResponse { 'timeSlots' : Array<string> }
export interface GetBookingsByCodeResponse { 'bookings' : Array<Booking> }
export interface GetServicesByArtistResponse { 'services' : Array<Service> }
export interface Gig {
  'id' : string,
  'title' : string,
  'artistId' : Principal,
  'description' : string,
  'deliveryTime' : Time,
  'pricing' : bigint,
}
export interface JobOffering {
  'id' : string,
  'description' : string,
  'deadline' : Time,
  'employer' : Principal,
  'jobTitle' : string,
  'budget' : bigint,
}
export interface Product {
  'id' : string,
  'title' : string,
  'artistId' : Principal,
  'productImages' : Array<ExternalBlob>,
  'description' : string,
  'price' : bigint,
}
export interface Range { 'end' : Time, 'start' : Time }
export interface SearchServicesByCategoryResponse {
  'services' : Array<Service>,
}
export interface Service {
  'id' : bigint,
  'duration' : bigint,
  'name' : string,
  'artistId' : Principal,
  'description' : string,
  'category' : [] | [string],
  'price' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateServiceRequest {
  'duration' : bigint,
  'name' : string,
  'description' : string,
  'category' : [] | [string],
  'price' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPortfolioImage' : ActorMethod<[ExternalBlob], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookService' : ActorMethod<[BookServiceRequest], undefined>,
  'calculateTimeRange' : ActorMethod<[CalculateTimeRangeRequest], undefined>,
  'createArtistProfile' : ActorMethod<
    [CreateArtistProfileRequest],
    CreateArtistProfileResponse
  >,
  'createBooking' : ActorMethod<[Booking], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createGig' : ActorMethod<[Gig], undefined>,
  'createJobOffering' : ActorMethod<[JobOffering], undefined>,
  'createProduct' : ActorMethod<
    [string, string, string, bigint, Array<ExternalBlob>],
    undefined
  >,
  'createService' : ActorMethod<[CreateServiceRequest], undefined>,
  'deleteBooking' : ActorMethod<[string], undefined>,
  'deleteGig' : ActorMethod<[string], undefined>,
  'deleteJobOffering' : ActorMethod<[string], undefined>,
  'deleteService' : ActorMethod<[DeleteServiceRequest], undefined>,
  'findBookingsByArtist' : ActorMethod<[Principal], Array<Booking>>,
  'findBookingsByDate' : ActorMethod<[], Array<Booking>>,
  'findGigsByDeliveryTime' : ActorMethod<[], Array<Gig>>,
  'findGigsByPricing' : ActorMethod<[], Array<Gig>>,
  'findJobOfferingsByBudget' : ActorMethod<[], Array<JobOffering>>,
  'findJobOfferingsByDeadline' : ActorMethod<[], Array<JobOffering>>,
  'findProductsByArtist' : ActorMethod<[Principal], Array<Product>>,
  'findProductsByPrice' : ActorMethod<[], Array<Product>>,
  'getAllArtists' : ActorMethod<[], AllArtistProfilesResponse>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllGigs' : ActorMethod<[], Array<Gig>>,
  'getAllJobOfferings' : ActorMethod<[], Array<JobOffering>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllServices' : ActorMethod<[], GetAllServicesResponse>,
  'getArtistById' : ActorMethod<[string], ArtistProfileResponse>,
  'getAvailableTimeSlots' : ActorMethod<[Range], GetAvailableTimeSlotsResponse>,
  'getBookingsByCode' : ActorMethod<[string], GetBookingsByCodeResponse>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getServicesByArtist' : ActorMethod<[Principal], GetServicesByArtistResponse>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'searchServicesByCategory' : ActorMethod<
    [string],
    SearchServicesByCategoryResponse
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBooking' : ActorMethod<[Booking], undefined>,
  'updateGig' : ActorMethod<[Gig], undefined>,
  'updateJobOffering' : ActorMethod<[JobOffering], undefined>,
  'updateService' : ActorMethod<[bigint, UpdateServiceRequest], undefined>,
  'uploadImage' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];