/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AllArtistProfilesResponse { 'profiles' : Array<ArtistProfile> }
export interface ArtistProfile {
  'id' : string,
  'bio' : string,
  'contactInfo' : string,
  'portfolioImages' : Array<ExternalBlob>,
  'skills' : Array<string>,
}
export interface ArtistProfileResponse { 'profile' : ArtistProfile }
export interface ArtistRevenue {
  'paidRevenue' : bigint,
  'artistId' : Principal,
  'pendingRevenue' : bigint,
  'totalRevenue' : bigint,
}
export interface BookServiceRequest {
  'date' : Time,
  'artistId' : Principal,
  'serviceId' : bigint,
}
export interface Booking {
  'id' : string,
  'serviceType' : string,
  'duration' : bigint,
  'clientId' : Principal,
  'date' : Time,
  'time' : string,
  'artistId' : Principal,
}
export interface CalculateTimeRangeRequest {
  'startTime' : string,
  'endDate' : Time,
  'endTime' : string,
  'startDate' : Time,
}
export interface CreateArtistProfileRequest {
  'bio' : string,
  'contactInfo' : string,
  'skills' : Array<string>,
}
export interface CreateArtistProfileResponse { 'id' : string }
export interface CreateServiceRequest {
  'duration' : bigint,
  'name' : string,
  'description' : string,
  'category' : [] | [string],
  'price' : bigint,
}
export interface DeleteServiceRequest { 'id' : bigint }
export type ExternalBlob = Uint8Array;
export interface GetAllServicesResponse { 'services' : Array<Service> }
export interface GetAvailableTimeSlotsResponse { 'timeSlots' : Array<string> }
export interface GetBookingsByCodeResponse { 'bookings' : Array<Booking> }
export interface GetServicesByArtistResponse { 'services' : Array<Service> }
export interface Gig {
  'id' : string,
  'title' : string,
  'artistId' : Principal,
  'description' : string,
  'deliveryTime' : Time,
  'pricing' : bigint,
}
export interface JobOffering {
  'id' : string,
  'description' : string,
  'deadline' : Time,
  'employer' : Principal,
  'jobTitle' : string,
  'budget' : bigint,
}
export interface Music {
  'id' : string,
  'title' : string,
  'audioFileBlob' : ExternalBlob,
  'description' : string,
  'category' : string,
  'artist' : Principal,
  'price' : bigint,
  'uploadDate' : bigint,
}
export interface PaymentTransaction {
  'id' : string,
  'transactionType' : { 'productSale' : null } |
    { 'donation' : null },
  'platformFee' : bigint,
  'artistId' : Principal,
  'productId' : string,
  'artistShare' : bigint,
  'buyerId' : Principal,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface PlatformRevenueMetrics {
  'averageTransactionValue' : bigint,
  'totalPlatformRevenue' : bigint,
  'totalArtistPayouts' : bigint,
  'totalTransactions' : bigint,
}
export interface PricingRule { 'maxPrice' : bigint, 'minPrice' : bigint }
export interface Product {
  'id' : string,
  'title' : string,
  'subcategory' : string,
  'artistId' : Principal,
  'productImages' : Array<ExternalBlob>,
  'description' : string,
  'price' : bigint,
}
export interface Range { 'end' : Time, 'start' : Time }
export interface SearchServicesByCategoryResponse {
  'services' : Array<Service>,
}
export interface Service {
  'id' : bigint,
  'duration' : bigint,
  'name' : string,
  'artistId' : Principal,
  'description' : string,
  'category' : [] | [string],
  'price' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SiteBranding {
  'primaryColor' : string,
  'description' : string,
  'siteName' : string,
  'logoUrl' : string,
  'secondaryColor' : string,
}
export interface StoreProductConfig {
  'productCategoryLimit' : bigint,
  'lowStockThreshold' : bigint,
  'returnPeriodDays' : bigint,
  'productCategories' : Array<string>,
  'freeShippingThreshold' : bigint,
  'productTags' : Array<string>,
  'artistRevenueSharePercentage' : bigint,
  'pricingRules' : PricingRule,
  'filterOptions' : Array<StoreProductFilter>,
  'inventoryTrackingEnabled' : boolean,
  'requireApprovalFor' : {
    'gigs' : boolean,
    'jobs' : boolean,
    'products' : boolean,
  },
  'defaultCurrency' : string,
  'featuredProducts' : Array<string>,
  'productStatuses' : Array<string>,
  'taxRate' : bigint,
}
export interface StoreProductFilter {
  'maxPrice' : [] | [bigint],
  'available' : [] | [boolean],
  'category' : [] | [string],
  'rating' : [] | [bigint],
  'minPrice' : [] | [bigint],
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface StripeStoreConfig {
  'webhookSecret' : string,
  'testMode' : boolean,
  'secretKey' : string,
  'currency' : string,
  'publishableKey' : string,
  'webhookEndpoint' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateArtistProfileRequest {
  'bio' : string,
  'contactInfo' : string,
  'portfolioImages' : Array<ExternalBlob>,
  'skills' : Array<string>,
}
export interface UpdateServiceRequest {
  'duration' : bigint,
  'name' : string,
  'description' : string,
  'category' : [] | [string],
  'price' : bigint,
}
export interface UserInfo {
  'principal' : Principal,
  'role' : UserRole,
  'hasArtistProfile' : boolean,
  'totalRevenue' : bigint,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPortfolioImage' : ActorMethod<[ExternalBlob], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookService' : ActorMethod<[BookServiceRequest], undefined>,
  'calculateTimeRange' : ActorMethod<[CalculateTimeRangeRequest], undefined>,
  'checkoutAndPayProduct' : ActorMethod<[string, string, string], string>,
  'createArtistProfile' : ActorMethod<
    [CreateArtistProfileRequest],
    CreateArtistProfileResponse
  >,
  'createBooking' : ActorMethod<[Booking], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createGig' : ActorMethod<[Gig], undefined>,
  'createJobOffering' : ActorMethod<[JobOffering], undefined>,
  'createMusic' : ActorMethod<
    [string, string, ExternalBlob, bigint, string, string],
    undefined
  >,
  'createProduct' : ActorMethod<
    [string, string, string, bigint, Array<ExternalBlob>, string],
    undefined
  >,
  'createProductFromImage' : ActorMethod<[string, ExternalBlob], undefined>,
  'createService' : ActorMethod<[CreateServiceRequest], undefined>,
  'deleteBooking' : ActorMethod<[string], undefined>,
  'deleteGig' : ActorMethod<[string], undefined>,
  'deleteJobOffering' : ActorMethod<[string], undefined>,
  'deleteMusic' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'deleteService' : ActorMethod<[DeleteServiceRequest], undefined>,
  'donateToArtist' : ActorMethod<[Principal, bigint, string, string], string>,
  'findBookingsByArtist' : ActorMethod<[Principal], Array<Booking>>,
  'findBookingsByDate' : ActorMethod<[], Array<Booking>>,
  'findGigsByDeliveryTime' : ActorMethod<[], Array<Gig>>,
  'findGigsByPricing' : ActorMethod<[], Array<Gig>>,
  'findJobOfferingsByBudget' : ActorMethod<[], Array<JobOffering>>,
  'findJobOfferingsByDeadline' : ActorMethod<[], Array<JobOffering>>,
  'findMusicByArtist' : ActorMethod<[Principal], Array<Music>>,
  'findMusicByPrice' : ActorMethod<[], Array<Music>>,
  'findProductsByArtist' : ActorMethod<[Principal], Array<Product>>,
  'findProductsByPrice' : ActorMethod<[], Array<Product>>,
  'getAllArtistRevenues' : ActorMethod<[], Array<ArtistRevenue>>,
  'getAllArtists' : ActorMethod<[], AllArtistProfilesResponse>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllGigs' : ActorMethod<[], Array<Gig>>,
  'getAllJobOfferings' : ActorMethod<[], Array<JobOffering>>,
  'getAllMusic' : ActorMethod<[], Array<Music>>,
  'getAllPaymentTransactions' : ActorMethod<[], Array<PaymentTransaction>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllServices' : ActorMethod<[], GetAllServicesResponse>,
  'getAllUsers' : ActorMethod<[], Array<UserInfo>>,
  'getArtistById' : ActorMethod<[string], ArtistProfileResponse>,
  'getArtistRevenue' : ActorMethod<[Principal], ArtistRevenue>,
  'getAvailableTimeSlots' : ActorMethod<[Range], GetAvailableTimeSlotsResponse>,
  'getBookingsByCode' : ActorMethod<[string], GetBookingsByCodeResponse>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMusicById' : ActorMethod<[string], [] | [Music]>,
  'getPaymentTransactionHistory' : ActorMethod<
    [Principal],
    Array<PaymentTransaction>
  >,
  'getPlatformRevenueMetrics' : ActorMethod<[], PlatformRevenueMetrics>,
  'getServicesByArtist' : ActorMethod<[Principal], GetServicesByArtistResponse>,
  'getSiteBranding' : ActorMethod<[], SiteBranding>,
  'getStoreProductConfig' : ActorMethod<[], StoreProductConfig>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getStripeStoreConfig' : ActorMethod<[], StripeStoreConfig>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchServicesByCategory' : ActorMethod<
    [string],
    SearchServicesByCategoryResponse
  >,
  'setArtistRevenueSharePercentage' : ActorMethod<[bigint], undefined>,
  'setPlatformCommissionRate' : ActorMethod<[bigint], undefined>,
  'setRequireApprovalFor' : ActorMethod<[boolean, boolean, boolean], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setStripeStoreConfig' : ActorMethod<[StripeStoreConfig], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateArtistProfile' : ActorMethod<[UpdateArtistProfileRequest], undefined>,
  'updateBooking' : ActorMethod<[Booking], undefined>,
  'updateGig' : ActorMethod<[Gig], undefined>,
  'updateJobOffering' : ActorMethod<[JobOffering], undefined>,
  'updateMusic' : ActorMethod<
    [string, string, bigint, string, string],
    undefined
  >,
  'updateProduct' : ActorMethod<
    [string, string, string, bigint, Array<ExternalBlob>, string],
    undefined
  >,
  'updateService' : ActorMethod<[bigint, UpdateServiceRequest], undefined>,
  'updateSiteBranding' : ActorMethod<[SiteBranding], undefined>,
  'updateStoreProductConfig' : ActorMethod<
    [
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      Array<StoreProductFilter>,
      PricingRule,
      Array<string>,
      Array<string>,
      Array<string>,
      Array<string>,
    ],
    undefined
  >,
  'uploadImage' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];