/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface GetAllServicesResponse {
    services: Array<Service>;
}
export interface Product {
    id: string;
    title: string;
    subcategory: string;
    artistId: Principal;
    productImages: Array<ExternalBlob>;
    description: string;
    price: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface GetAvailableTimeSlotsResponse {
    timeSlots: Array<string>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface CreateArtistProfileRequest {
    bio: string;
    contactInfo: string;
    skills: Array<string>;
}
export interface CalculateTimeRangeRequest {
    startTime: string;
    endDate: Time;
    endTime: string;
    startDate: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface BookServiceRequest {
    date: Time;
    artistId: Principal;
    serviceId: bigint;
}
export interface UpdateServiceRequest {
    duration: bigint;
    name: string;
    description: string;
    category?: string;
    price: bigint;
}
export interface ArtistProfileResponse {
    profile: ArtistProfile;
}
export interface StoreProductConfig {
    productCategoryLimit: bigint;
    lowStockThreshold: bigint;
    returnPeriodDays: bigint;
    productCategories: Array<string>;
    freeShippingThreshold: bigint;
    productTags: Array<string>;
    pricingRules: PricingRule;
    filterOptions: Array<StoreProductFilter>;
    inventoryTrackingEnabled: boolean;
    requireApprovalFor: {
        gigs: boolean;
        jobs: boolean;
        products: boolean;
    };
    defaultCurrency: string;
    featuredProducts: Array<string>;
    productStatuses: Array<string>;
    taxRate: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Gig {
    id: string;
    title: string;
    artistId: Principal;
    description: string;
    deliveryTime: Time;
    pricing: bigint;
}
export interface DeleteServiceRequest {
    id: bigint;
}
export interface Booking {
    id: string;
    serviceType: string;
    duration: bigint;
    clientId: Principal;
    date: Time;
    time: string;
    artistId: Principal;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface JobOffering {
    id: string;
    description: string;
    deadline: Time;
    employer: Principal;
    jobTitle: string;
    budget: bigint;
}
export interface CreateServiceRequest {
    duration: bigint;
    name: string;
    description: string;
    category?: string;
    price: bigint;
}
export interface CreateArtistProfileResponse {
    id: string;
}
export interface AllArtistProfilesResponse {
    profiles: Array<ArtistProfile>;
}
export interface StoreProductFilter {
    maxPrice?: bigint;
    available?: boolean;
    category?: string;
    rating?: bigint;
    minPrice?: bigint;
}
export interface SearchServicesByCategoryResponse {
    services: Array<Service>;
}
export interface GetBookingsByCodeResponse {
    bookings: Array<Booking>;
}
export interface StripeStoreConfig {
    webhookSecret: string;
    testMode: boolean;
    secretKey: string;
    currency: string;
    publishableKey: string;
    webhookEndpoint: string;
}
export interface Service {
    id: bigint;
    duration: bigint;
    name: string;
    artistId: Principal;
    description: string;
    category?: string;
    price: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface Range {
    end: Time;
    start: Time;
}
export interface GetServicesByArtistResponse {
    services: Array<Service>;
}
export interface ArtistProfile {
    id: string;
    bio: string;
    contactInfo: string;
    portfolioImages: Array<ExternalBlob>;
    skills: Array<string>;
}
export interface PricingRule {
    maxPrice: bigint;
    minPrice: bigint;
}
export interface Music {
    id: string;
    title: string;
    audioFileBlob: ExternalBlob;
    description: string;
    category: string;
    artist: Principal;
    price: bigint;
    uploadDate: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPortfolioImage(blob: ExternalBlob): Promise<void>;
    assignAdminPrivileges(adminPrincipal: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookService(request: BookServiceRequest): Promise<void>;
    calculateTimeRange(arg0: CalculateTimeRangeRequest): Promise<void>;
    createArtistProfile(artist: CreateArtistProfileRequest): Promise<CreateArtistProfileResponse>;
    createBooking(booking: Booking): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createGig(gig: Gig): Promise<void>;
    createJobOffering(offering: JobOffering): Promise<void>;
    createMusic(id: string, title: string, audioFileBlob: ExternalBlob, price: bigint, description: string, category: string): Promise<void>;
    createProduct(id: string, title: string, description: string, price: bigint, productImages: Array<ExternalBlob>, subcategory: string): Promise<void>;
    createProductFromImage(productId: string, image: ExternalBlob): Promise<void>;
    createService(request: CreateServiceRequest): Promise<void>;
    deleteBooking(id: string): Promise<void>;
    deleteGig(id: string): Promise<void>;
    deleteJobOffering(id: string): Promise<void>;
    deleteMusic(id: string): Promise<void>;
    deleteProduct(id: string): Promise<void>;
    deleteService(request: DeleteServiceRequest): Promise<void>;
    findBookingsByArtist(artistId: Principal): Promise<Array<Booking>>;
    findBookingsByDate(): Promise<Array<Booking>>;
    findGigsByDeliveryTime(): Promise<Array<Gig>>;
    findGigsByPricing(): Promise<Array<Gig>>;
    findJobOfferingsByBudget(): Promise<Array<JobOffering>>;
    findJobOfferingsByDeadline(): Promise<Array<JobOffering>>;
    findMusicByArtist(artist: Principal): Promise<Array<Music>>;
    findMusicByPrice(): Promise<Array<Music>>;
    findProductsByArtist(artistId: Principal): Promise<Array<Product>>;
    findProductsByPrice(): Promise<Array<Product>>;
    getAllArtists(): Promise<AllArtistProfilesResponse>;
    getAllBookings(): Promise<Array<Booking>>;
    getAllGigs(): Promise<Array<Gig>>;
    getAllJobOfferings(): Promise<Array<JobOffering>>;
    getAllMusic(): Promise<Array<Music>>;
    getAllProducts(): Promise<Array<Product>>;
    getAllServices(): Promise<GetAllServicesResponse>;
    getArtistById(id: string): Promise<ArtistProfileResponse>;
    getAvailableTimeSlots(arg0: Range): Promise<GetAvailableTimeSlotsResponse>;
    getBookingsByCode(arg0: string): Promise<GetBookingsByCodeResponse>;
    getCallerUserRole(): Promise<UserRole>;
    getMusicById(id: string): Promise<Music | null>;
    getServicesByArtist(artistId: Principal): Promise<GetServicesByArtistResponse>;
    getStoreProductConfig(): Promise<StoreProductConfig>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getStripeStoreConfig(): Promise<StripeStoreConfig>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    searchServicesByCategory(category: string): Promise<SearchServicesByCategoryResponse>;
    setRequireApprovalFor(jobs: boolean, products: boolean, gigs: boolean): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    setStripeStoreConfig(config: StripeStoreConfig): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateBooking(booking: Booking): Promise<void>;
    updateGig(gig: Gig): Promise<void>;
    updateJobOffering(offering: JobOffering): Promise<void>;
    updateMusic(id: string, newTitle: string, newPrice: bigint, newDescription: string, newCategory: string): Promise<void>;
    updateProduct(id: string, title: string, description: string, price: bigint, productImages: Array<ExternalBlob>, subcategory: string): Promise<void>;
    updateService(id: bigint, request: UpdateServiceRequest): Promise<void>;
    updateStoreProductConfig(inventoryThreshold: bigint, freeShippingAmount: bigint, taxRate: bigint, categoryLimit: bigint, returnDays: bigint, pricingRules: PricingRule, productCategories: Array<string>, productTags: Array<string>, featuredProducts: Array<string>, productStatuses: Array<string>): Promise<void>;
    uploadImage(blob: ExternalBlob): Promise<void>;
}
import type { AllArtistProfilesResponse as _AllArtistProfilesResponse, ArtistProfile as _ArtistProfile, ArtistProfileResponse as _ArtistProfileResponse, CreateServiceRequest as _CreateServiceRequest, ExternalBlob as _ExternalBlob, GetAllServicesResponse as _GetAllServicesResponse, GetServicesByArtistResponse as _GetServicesByArtistResponse, Music as _Music, PricingRule as _PricingRule, Product as _Product, SearchServicesByCategoryResponse as _SearchServicesByCategoryResponse, Service as _Service, StoreProductConfig as _StoreProductConfig, StoreProductFilter as _StoreProductFilter, StripeSessionStatus as _StripeSessionStatus, UpdateServiceRequest as _UpdateServiceRequest, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPortfolioImage(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPortfolioImage(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPortfolioImage(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignAdminPrivileges(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignAdminPrivileges(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignAdminPrivileges(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookService(arg0: BookServiceRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bookService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookService(arg0);
            return result;
        }
    }
    async calculateTimeRange(arg0: CalculateTimeRangeRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateTimeRange(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateTimeRange(arg0);
            return result;
        }
    }
    async createArtistProfile(arg0: CreateArtistProfileRequest): Promise<CreateArtistProfileResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.createArtistProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createArtistProfile(arg0);
            return result;
        }
    }
    async createBooking(arg0: Booking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createGig(arg0: Gig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createGig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGig(arg0);
            return result;
        }
    }
    async createJobOffering(arg0: JobOffering): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobOffering(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobOffering(arg0);
            return result;
        }
    }
    async createMusic(arg0: string, arg1: string, arg2: ExternalBlob, arg3: bigint, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMusic(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMusic(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
            return result;
        }
    }
    async createProduct(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: Array<ExternalBlob>, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0, arg1, arg2, arg3, await to_candid_vec_n11(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0, arg1, arg2, arg3, await to_candid_vec_n11(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async createProductFromImage(arg0: string, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProductFromImage(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProductFromImage(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createService(arg0: CreateServiceRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createService(to_candid_CreateServiceRequest_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createService(to_candid_CreateServiceRequest_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteBooking(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBooking(arg0);
            return result;
        }
    }
    async deleteGig(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGig(arg0);
            return result;
        }
    }
    async deleteJobOffering(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJobOffering(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJobOffering(arg0);
            return result;
        }
    }
    async deleteMusic(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMusic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMusic(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteService(arg0: DeleteServiceRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteService(arg0);
            return result;
        }
    }
    async findBookingsByArtist(arg0: Principal): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.findBookingsByArtist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findBookingsByArtist(arg0);
            return result;
        }
    }
    async findBookingsByDate(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.findBookingsByDate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findBookingsByDate();
            return result;
        }
    }
    async findGigsByDeliveryTime(): Promise<Array<Gig>> {
        if (this.processError) {
            try {
                const result = await this.actor.findGigsByDeliveryTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findGigsByDeliveryTime();
            return result;
        }
    }
    async findGigsByPricing(): Promise<Array<Gig>> {
        if (this.processError) {
            try {
                const result = await this.actor.findGigsByPricing();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findGigsByPricing();
            return result;
        }
    }
    async findJobOfferingsByBudget(): Promise<Array<JobOffering>> {
        if (this.processError) {
            try {
                const result = await this.actor.findJobOfferingsByBudget();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findJobOfferingsByBudget();
            return result;
        }
    }
    async findJobOfferingsByDeadline(): Promise<Array<JobOffering>> {
        if (this.processError) {
            try {
                const result = await this.actor.findJobOfferingsByDeadline();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findJobOfferingsByDeadline();
            return result;
        }
    }
    async findMusicByArtist(arg0: Principal): Promise<Array<Music>> {
        if (this.processError) {
            try {
                const result = await this.actor.findMusicByArtist(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findMusicByArtist(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async findMusicByPrice(): Promise<Array<Music>> {
        if (this.processError) {
            try {
                const result = await this.actor.findMusicByPrice();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findMusicByPrice();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async findProductsByArtist(arg0: Principal): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.findProductsByArtist(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findProductsByArtist(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async findProductsByPrice(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.findProductsByPrice();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findProductsByPrice();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllArtists(): Promise<AllArtistProfilesResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllArtists();
                return from_candid_AllArtistProfilesResponse_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllArtists();
            return from_candid_AllArtistProfilesResponse_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return result;
        }
    }
    async getAllGigs(): Promise<Array<Gig>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGigs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGigs();
            return result;
        }
    }
    async getAllJobOfferings(): Promise<Array<JobOffering>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobOfferings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobOfferings();
            return result;
        }
    }
    async getAllMusic(): Promise<Array<Music>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMusic();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMusic();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllServices(): Promise<GetAllServicesResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServices();
                return from_candid_GetAllServicesResponse_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServices();
            return from_candid_GetAllServicesResponse_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArtistById(arg0: string): Promise<ArtistProfileResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getArtistById(arg0);
                return from_candid_ArtistProfileResponse_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArtistById(arg0);
            return from_candid_ArtistProfileResponse_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableTimeSlots(arg0: Range): Promise<GetAvailableTimeSlotsResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableTimeSlots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableTimeSlots(arg0);
            return result;
        }
    }
    async getBookingsByCode(arg0: string): Promise<GetBookingsByCodeResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByCode(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMusicById(arg0: string): Promise<Music | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMusicById(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMusicById(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServicesByArtist(arg0: Principal): Promise<GetServicesByArtistResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getServicesByArtist(arg0);
                return from_candid_GetServicesByArtistResponse_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServicesByArtist(arg0);
            return from_candid_GetServicesByArtistResponse_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStoreProductConfig(): Promise<StoreProductConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoreProductConfig();
                return from_candid_StoreProductConfig_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoreProductConfig();
            return from_candid_StoreProductConfig_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeStoreConfig(): Promise<StripeStoreConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeStoreConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeStoreConfig();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async searchServicesByCategory(arg0: string): Promise<SearchServicesByCategoryResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.searchServicesByCategory(arg0);
                return from_candid_SearchServicesByCategoryResponse_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchServicesByCategory(arg0);
            return from_candid_SearchServicesByCategoryResponse_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async setRequireApprovalFor(arg0: boolean, arg1: boolean, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRequireApprovalFor(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRequireApprovalFor(arg0, arg1, arg2);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async setStripeStoreConfig(arg0: StripeStoreConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeStoreConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeStoreConfig(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBooking(arg0: Booking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBooking(arg0);
            return result;
        }
    }
    async updateGig(arg0: Gig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGig(arg0);
            return result;
        }
    }
    async updateJobOffering(arg0: JobOffering): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobOffering(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobOffering(arg0);
            return result;
        }
    }
    async updateMusic(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMusic(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMusic(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateProduct(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: Array<ExternalBlob>, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, await to_candid_vec_n11(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, await to_candid_vec_n11(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async updateService(arg0: bigint, arg1: UpdateServiceRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(arg0, to_candid_UpdateServiceRequest_n48(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(arg0, to_candid_UpdateServiceRequest_n48(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateStoreProductConfig(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: PricingRule, arg6: Array<string>, arg7: Array<string>, arg8: Array<string>, arg9: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStoreProductConfig(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStoreProductConfig(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async uploadImage(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadImage(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadImage(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_AllArtistProfilesResponse_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AllArtistProfilesResponse): Promise<AllArtistProfilesResponse> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_ArtistProfileResponse_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArtistProfileResponse): Promise<ArtistProfileResponse> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function from_candid_ArtistProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArtistProfile): Promise<ArtistProfile> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_GetAllServicesResponse_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GetAllServicesResponse): GetAllServicesResponse {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_GetServicesByArtistResponse_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GetServicesByArtistResponse): GetServicesByArtistResponse {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_Music_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Music): Promise<Music> {
    return await from_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_SearchServicesByCategoryResponse_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SearchServicesByCategoryResponse): SearchServicesByCategoryResponse {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_StoreProductConfig_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoreProductConfig): StoreProductConfig {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_StoreProductFilter_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoreProductFilter): StoreProductFilter {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Music]): Promise<Music | null> {
    return value.length === 0 ? null : await from_candid_Music_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    audioFileBlob: _ExternalBlob;
    description: string;
    category: string;
    artist: Principal;
    price: bigint;
    uploadDate: bigint;
}): Promise<{
    id: string;
    title: string;
    audioFileBlob: ExternalBlob;
    description: string;
    category: string;
    artist: Principal;
    price: bigint;
    uploadDate: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        audioFileBlob: await from_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.audioFileBlob),
        description: value.description,
        category: value.category,
        artist: value.artist,
        price: value.price,
        uploadDate: value.uploadDate
    };
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    subcategory: string;
    artistId: Principal;
    productImages: Array<_ExternalBlob>;
    description: string;
    price: bigint;
}): Promise<{
    id: string;
    title: string;
    subcategory: string;
    artistId: Principal;
    productImages: Array<ExternalBlob>;
    description: string;
    price: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        subcategory: value.subcategory,
        artistId: value.artistId,
        productImages: await from_candid_vec_n21(_uploadFile, _downloadFile, value.productImages),
        description: value.description,
        price: value.price
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    profiles: Array<_ArtistProfile>;
}): Promise<{
    profiles: Array<ArtistProfile>;
}> {
    return {
        profiles: await from_candid_vec_n24(_uploadFile, _downloadFile, value.profiles)
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    contactInfo: string;
    portfolioImages: Array<_ExternalBlob>;
    skills: Array<string>;
}): Promise<{
    id: string;
    bio: string;
    contactInfo: string;
    portfolioImages: Array<ExternalBlob>;
    skills: Array<string>;
}> {
    return {
        id: value.id,
        bio: value.bio,
        contactInfo: value.contactInfo,
        portfolioImages: await from_candid_vec_n21(_uploadFile, _downloadFile, value.portfolioImages),
        skills: value.skills
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    services: Array<_Service>;
}): {
    services: Array<Service>;
} {
    return {
        services: from_candid_vec_n29(_uploadFile, _downloadFile, value.services)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    duration: bigint;
    name: string;
    artistId: Principal;
    description: string;
    category: [] | [string];
    price: bigint;
}): {
    id: bigint;
    duration: bigint;
    name: string;
    artistId: Principal;
    description: string;
    category?: string;
    price: bigint;
} {
    return {
        id: value.id,
        duration: value.duration,
        name: value.name,
        artistId: value.artistId,
        description: value.description,
        category: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.category)),
        price: value.price
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    profile: _ArtistProfile;
}): Promise<{
    profile: ArtistProfile;
}> {
    return {
        profile: await from_candid_ArtistProfile_n25(_uploadFile, _downloadFile, value.profile)
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    productCategoryLimit: bigint;
    lowStockThreshold: bigint;
    returnPeriodDays: bigint;
    productCategories: Array<string>;
    freeShippingThreshold: bigint;
    productTags: Array<string>;
    pricingRules: _PricingRule;
    filterOptions: Array<_StoreProductFilter>;
    inventoryTrackingEnabled: boolean;
    requireApprovalFor: {
        gigs: boolean;
        jobs: boolean;
        products: boolean;
    };
    defaultCurrency: string;
    featuredProducts: Array<string>;
    productStatuses: Array<string>;
    taxRate: bigint;
}): {
    productCategoryLimit: bigint;
    lowStockThreshold: bigint;
    returnPeriodDays: bigint;
    productCategories: Array<string>;
    freeShippingThreshold: bigint;
    productTags: Array<string>;
    pricingRules: PricingRule;
    filterOptions: Array<StoreProductFilter>;
    inventoryTrackingEnabled: boolean;
    requireApprovalFor: {
        gigs: boolean;
        jobs: boolean;
        products: boolean;
    };
    defaultCurrency: string;
    featuredProducts: Array<string>;
    productStatuses: Array<string>;
    taxRate: bigint;
} {
    return {
        productCategoryLimit: value.productCategoryLimit,
        lowStockThreshold: value.lowStockThreshold,
        returnPeriodDays: value.returnPeriodDays,
        productCategories: value.productCategories,
        freeShippingThreshold: value.freeShippingThreshold,
        productTags: value.productTags,
        pricingRules: value.pricingRules,
        filterOptions: from_candid_vec_n41(_uploadFile, _downloadFile, value.filterOptions),
        inventoryTrackingEnabled: value.inventoryTrackingEnabled,
        requireApprovalFor: value.requireApprovalFor,
        defaultCurrency: value.defaultCurrency,
        featuredProducts: value.featuredProducts,
        productStatuses: value.productStatuses,
        taxRate: value.taxRate
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maxPrice: [] | [bigint];
    available: [] | [boolean];
    category: [] | [string];
    rating: [] | [bigint];
    minPrice: [] | [bigint];
}): {
    maxPrice?: bigint;
    available?: boolean;
    category?: string;
    rating?: bigint;
    minPrice?: bigint;
} {
    return {
        maxPrice: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.maxPrice)),
        available: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.available)),
        category: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.category)),
        rating: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.rating)),
        minPrice: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.minPrice))
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n46(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
async function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Music>): Promise<Array<Music>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Music_n15(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n19(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n17(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ArtistProfile>): Promise<Array<ArtistProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ArtistProfile_n25(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Array<Service> {
    return value.map((x)=>from_candid_Service_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StoreProductFilter>): Array<StoreProductFilter> {
    return value.map((x)=>from_candid_StoreProductFilter_n42(_uploadFile, _downloadFile, x));
}
function to_candid_CreateServiceRequest_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateServiceRequest): _CreateServiceRequest {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UpdateServiceRequest_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateServiceRequest): _UpdateServiceRequest {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duration: bigint;
    name: string;
    description: string;
    category?: string;
    price: bigint;
}): {
    duration: bigint;
    name: string;
    description: string;
    category: [] | [string];
    price: bigint;
} {
    return {
        duration: value.duration,
        name: value.name,
        description: value.description,
        category: value.category ? candid_some(value.category) : candid_none(),
        price: value.price
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
